
<script setup>
import $ from 'jquery'

const route = useRoute()
</script>

<template>


  <div v-if="route.name !== 'browserCheck'">
     <div class="wrapper" style="min-height: calc(100vh - 298px)">
       <header>
         <Header />
       </header>

       <NuxtPage />

     </div>

     <footer>
       <Footer :cb=true />
     </footer>
  </div>
  <div v-else>
    <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
  <div style="text-align: center">
    <img src="/static/images/logos/logo.png" alt="MineHQ Logo">
    <div style="transform: scale(0.3)">
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; display: block; shape-rendering: auto;" width="101px" height="101px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
        <g transform="rotate(0 50 50)">
          <rect x="47.5" y="15" rx="0" ry="0" width="5" height="18" fill="#727272">
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.9166666666666666s" repeatCount="indefinite"></animate>
          </rect>
        </g><g transform="rotate(30 50 50)">
        <rect x="47.5" y="15" rx="0" ry="0" width="5" height="18" fill="#727272">
          <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.8333333333333334s" repeatCount="indefinite"></animate>
        </rect>
      </g><g transform="rotate(60 50 50)">
        <rect x="47.5" y="15" rx="0" ry="0" width="5" height="18" fill="#727272">
          <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.75s" repeatCount="indefinite"></animate>
        </rect>
      </g><g transform="rotate(90 50 50)">
        <rect x="47.5" y="15" rx="0" ry="0" width="5" height="18" fill="#727272">
          <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.6666666666666666s" repeatCount="indefinite"></animate>
        </rect>
      </g><g transform="rotate(120 50 50)">
        <rect x="47.5" y="15" rx="0" ry="0" width="5" height="18" fill="#727272">
          <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.5833333333333334s" repeatCount="indefinite"></animate>
        </rect>
      </g><g transform="rotate(150 50 50)">
        <rect x="47.5" y="15" rx="0" ry="0" width="5" height="18" fill="#727272">
          <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.5s" repeatCount="indefinite"></animate>
        </rect>
      </g><g transform="rotate(180 50 50)">
        <rect x="47.5" y="15" rx="0" ry="0" width="5" height="18" fill="#727272">
          <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.4166666666666667s" repeatCount="indefinite"></animate>
        </rect>
      </g><g transform="rotate(210 50 50)">
        <rect x="47.5" y="15" rx="0" ry="0" width="5" height="18" fill="#727272">
          <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.3333333333333333s" repeatCount="indefinite"></animate>
        </rect>
      </g><g transform="rotate(240 50 50)">
        <rect x="47.5" y="15" rx="0" ry="0" width="5" height="18" fill="#727272">
          <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.25s" repeatCount="indefinite"></animate>
        </rect>
      </g><g transform="rotate(270 50 50)">
        <rect x="47.5" y="15" rx="0" ry="0" width="5" height="18" fill="#727272">
          <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.16666666666666666s" repeatCount="indefinite"></animate>
        </rect>
      </g><g transform="rotate(300 50 50)">
        <rect x="47.5" y="15" rx="0" ry="0" width="5" height="18" fill="#727272">
          <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.08333333333333333s" repeatCount="indefinite"></animate>
        </rect>
      </g><g transform="rotate(330 50 50)">
        <rect x="47.5" y="15" rx="0" ry="0" width="5" height="18" fill="#727272">
          <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="0s" repeatCount="indefinite"></animate>
        </rect>
      </g>
        <!-- [ldio] generated by https://loading.io/ --></svg>
    </div>

    <div style="font-family: Arial, Helvetica, sans-serif; font-style: normal;">
      <div style="font-size: 21px; font: medium">
        Some nerds are trying to hit us off right now...
      </div>
      <br>
      Give us a few seconds to check your browser and make sure you're not one of them.
    </div>
  </div>
</div>
  </div>
</template>

<style>

@import "/static/css/font-awesome.css";
@import "/static/css/fonts.css";
@import "/static/css/schedule.css";
@import "/static/css/style.css";

</style>